services:
  flyway:
    build:
      context: .
      dockerfile: Dockerfile.flyway
    volumes:
      - ./resources/migration/sql:/flyway/sql
      - ./resources/migration/callbacks:/flyway/sql/callbacks/
      - ./resources/flyway.conf:/flyway/conf/flyway.conf
    env_file:
      - ${ENV_PROPERTIES}
    command: migrate
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles: ["migrate"]